### ISSUE TITLE
Redirect loop on iOS

### ISSUE THREAD

**Issue by kkaefer** [bkeepers/github-notifications#139]
When loading the page in safari on iOS, it goes in to a redirect loop bouncing back and forth between Github and the notifications app. I tried deleting the website data and the history, but to no avail.

**Comment by bkeepers** [comment]
Weird. Do you have anything disabled in Safari, like cookies or JavaScript?

**Comment by kkaefer** [comment]
Nope; I've been using this app for months on my phone issues. Cookies and JavaScript are enabled. I cleared website data as well, but still seeing the bouncing back and forth.

**Comment by bkeepers** [comment]
I just cleared localstorage on my desktop and am seeing the redirect loop now as well.

**Comment by BergWerkGIS** [comment]
Same on Windows 7 64bit and Windows 8.1 64bit:
Chrome 40.0.2214.111 - with AdBlock
Chrome 42.0.2298.0 canary (64-bit) - with AdBlock
FF 35.0.1 - no Add-ons
IE 11.0.9600.17501 - no Add-ons

![redirect-loop](https://cloud.githubusercontent.com/assets/4549888/6097048/b9eb5972-afad-11e4-9ccf-6b44341beca7.gif)
