### ISSUE TITLE
Rolling Session ID 

### ISSUE THREAD

**Issue by mattgraham** [bkeepers/github-notifications#143]
![ghn](https://cloud.githubusercontent.com/assets/51578/6289073/8af82734-b8eb-11e4-9977-70c29328a6a3.gif)

When running locally I'm getting a rolling session ID without anything loading on the page.

**Comment by bkeepers** [comment]
This is the same as #139. I haven't been able to dig into it.

**Comment by mattgraham** [comment]
:+1:
