### ISSUE TITLE
Shortcut for unsubscribe

### ISSUE THREAD

**Issue by kkaefer** [bkeepers/github-notifications#148]
It’d be cool to have a keyboard shortcut for unsubscribing from the currently shown issue.

<table>
  <tr>
    <th>Browser</th>
    <td>Mozilla&#x2F;5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit&#x2F;537.36 (KHTML, like Gecko) Chrome&#x2F;41.0.2272.118 Safari&#x2F;537.36</td>
  </tr>
</table>

**Comment by michaeltwofish** [comment]
@kkaefer is `m` for mute what you want?

**Comment by kkaefer** [comment]
Yep.

**Comment by kkaefer** [comment]
It's not listed on the Keyboard Shortcuts page though

**Comment by michaeltwofish** [comment]
Yeah, I think this is what bit me in https://github.com/bkeepers/github-notifications/issues/81, which I'd forgotten about. Thanks for the bump!
