### ISSUE TITLE
Icons in notifications list doesn't represent state

### ISSUE THREAD

**Issue by jerone** [bkeepers/github-notifications#155]
The octicons indicating an issue and PR in the notifications list don't represent the state the notification is in. For an issue the icon is always green, while the issue could be closed, which should be red. Same goes for PR's which are purple indicating that the PR is merged, while it could still be closed or open (see screenshot below). I find this very confusing.

![github notifications](https://cloud.githubusercontent.com/assets/55841/10558268/42405d72-74ca-11e5-90fd-798067b8bcbc.png)

GitHub self shows the icons as normal black when grouping them together:
![2015-10-17 12_28_00-bkeepers_github-notifications](https://cloud.githubusercontent.com/assets/55841/10558285/9c55c810-74ca-11e5-9cd2-8b927d8c115d.png)

Another solution is to make the icons color indicate the real state of the issue (open/closed) or PR (open/closed/merged).

**Comment by jerone** [comment]
I made https://github.com/jerone/github-notifications/commit/ed458d78067aec2ad76a1115d86911750dad1cd6 which resets the octicons colors to black/grey. If you think this is the way to go I can send a PR.

**Comment by bkeepers** [comment]
> Another solution is to make the icons color indicate the real state of the issue (open/closed) or PR (open/closed/merged).

This would be my preference, but I don't think the notification API includes the state, so it would require n+1 API calls for showing the notification list.
