### ISSUE TITLE
All keyboard shortcuts should show up in help 

### ISSUE THREAD

**Issue by WillAbides** [bkeepers/github-notifications#160]
Help for keyboard shortcuts is missing the shorcuts [defined here](https://github.com/bkeepers/github-notifications/blob/6055b9ff198214802f7500a4862bcbf4ac86b59a/app/js/views/notification_details.coffee#L6).

![2016-02-29 at 7 06 am](https://cloud.githubusercontent.com/assets/233500/13395237/26227884-deb3-11e5-88d6-679f53632839.png)

**Comment by michaeltwofish** [comment]
This is a dupe of https://github.com/bkeepers/github-notifications/issues/81.

**Comment by WillAbides** [comment]
Thanks, @michaeltwofish.  Closing this and yielding to #81.
